import Sidebar from "./Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="root-layout">
          <div className="sidebar">
            <Sidebar />
          </div>
          <div className="content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
